//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessia2Malev
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventNew
    {
        public int EventID { get; set; }
        public string Event { get; set; }
        public System.DateTime DateEvent { get; set; }
        public int RoleID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
