//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessia2Malev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalevEntities : DbContext
    {
        public MalevEntities()
            : base("name=MalevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuildingType> BuildingType { get; set; }
        public virtual DbSet<ConnectedService> ConnectedService { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<ContractType> ContractType { get; set; }
        public virtual DbSet<CRM> CRM { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentType> EquipmentType { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventNew> EventNew { get; set; }
        public virtual DbSet<EventRole> EventRole { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<ProblemType> ProblemType { get; set; }
        public virtual DbSet<Raion> Raion { get; set; }
        public virtual DbSet<ReasonForTermination> ReasonForTermination { get; set; }
        public virtual DbSet<ResidentalAddress> ResidentalAddress { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<StatusService> StatusService { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<Subscriber> Subscriber { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfService> TypeOfService { get; set; }
        public virtual DbSet<TypeService> TypeService { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<InstallationEquipment> InstallationEquipment { get; set; }
    }
}
