//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessia2Malev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Raion()
        {
            this.ResidentalAddress = new HashSet<ResidentalAddress>();
        }
    
        public int RaionID { get; set; }
        public string Raion1 { get; set; }
        public double Square { get; set; }
        public int Population { get; set; }
        public int MetroStation { get; set; }
        public int BuildingTypeID { get; set; }
    
        public virtual BuildingType BuildingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentalAddress> ResidentalAddress { get; set; }
    }
}
