//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessia2Malev
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentalAddress
    {
        public string ResidentalAddressID { get; set; }
        public string PrefixCode { get; set; }
        public int RaionID { get; set; }
        public string City { get; set; }
        public int StreetID { get; set; }
        public string House { get; set; }
    
        public virtual Raion Raion { get; set; }
        public virtual Street Street { get; set; }
    }
}
